language: ruby
rvm:
- 2.5
services:
- postgresql
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
script:
- bundle config set deployment 'true'
- bundle exec rspec
- bundle exec rubocop
branches:
  only:
  - master